### ISSUE TITLE
Remove objective C dependency

### ISSUE THREAD

**Issue by nanoscopic** [nanoscopic/iosif#3]
Currently Objective C is used for NSKeyedArchival / Unarchival.
I'd prefer not to have to depend on anything not plain C; so would like to either integrate a library that does this in C ( or implement my own... )

**Comment by Dantee296** [comment]
@nanoscopic can u provide any refering library in c++ , which can do this 
i m stuck at NSKeyArchiver on Windows

**Comment by nanoscopic** [comment]
The latest release already includes an "NSKeyedArchiver" in the form of archiver.h and archiver.c.

It does not, though, include yet an "NSKeyedUnarchiver". I will be writing one. Initially the way it will work is:
1. Read binary plist NSKeyedArchive format using CF binary plist.
2. Output to XML plist format
3. Parse XML plist format using uxmlin
4. Convert to archive.h structure I am using for archiving.

**Comment by nanoscopic** [comment]
This has been done and is in the current code. Objective C is no longer used for archival or unarchival.
