### ISSUE TITLE
Crash within dearchive

### ISSUE THREAD

**Issue by Dantee296** [nanoscopic/iosif#5]
figured it out

**Comment by nanoscopic** [comment]
While you have figured it out; I did notice that you were implementing launch process. I was/am already in process of doing that so I've gone ahead and added, committed, and pushed the code I wrote to do so.

I had need of it for implementing launch of WDA, which will be coming soon also.

**Comment by Dantee296** [comment]
@nanoscopic have u also implemented list app service ?  com.apple.instruments.server.services.device.applictionListing 
if yes please provide commit for that one . 

returning this error and crashing

Float with numBytes 32768
Could not fetch item 1531
Could not fetch item 1535
in  **dearchive** method

**Comment by Dantee296** [comment]
"com.apple.instruments.server.services.deviceinfo
systemInformation

crashing as well 
0111 ??
0111 ??

**Comment by nanoscopic** [comment]
Listing applications is already there. `iosif listapps`

You'll need to explain a few things for me to determine what is causing the crash you are seeing:
1. What command did you run that resulted in the given error
2. Are you running against a real device or a simulator? If real device, what model and what iOS version?

If the crash is occurring within dearchive, then I can add some diagnostics to dump out the data that cannot be successfully dearchived. I'd need to have that data sample to determine why it fails to dearchive.

**Comment by Dantee296** [comment]
```
void getdeviceinfo( void *device ) {
   if( !desired_device( device, g_cmd ) ) {   printf("udid not found!\n"); return; }
  
  serviceT *service = service__new_instruments( device );
  channelT *chan = service__connect_channel( service, "com.apple.instruments.server.services.deviceinfo" );
  
  //CFTypeRef ls;
  tBASE *ls;
  channel__call( chan,
    "systemInformation", NULL, 0,
    &ls, NULL
  );
  //cfdump( 1, ls );
  tBASE__dump( ls, 1 );
  
  service__del( service );
  exit(0);
}
```
running on a real device iphone xs max 13.3 , developer image mounted

bpList *list = bpList__new( data, len ); this line returns 

0111 ??
0111 ??

```
**DEBUG MODE RESPONCE**
raw data:bplist00
X$versionY$archiverT$topX$objects
0111 ??
0111 ??
{
  $version:100000
  $archiver:"NSKeyedArchiver"
  $top:{
    root:oid.1
}
  $objects:[
    "$null"
    {
      NS.keys:[
        oid.2
        oid.3
        oid.4
        oid.5
        oid.6
        oid.7
        oid.8
      ]
      NS.objects:[
        oid.9
        oid.10
        oid.11
        oid.12
        oid.13
        oid.14
        oid.15
      ]
      $class:oid.16
}
    "_productVersion"
    "_productType"
    "_deviceDescription"
    "_xrdeviceClassName"
    "_deviceDisplayName"
    "_deviceVersion"
    "_deviceIdentifier"
    "13.3"
    "iPhone11,6"
    "Build Version 17C54, iPhone ID 00008020-00110CC811D0003A"
    "XRMobileDevice"
    0.00
    0.00
    0.00
  ]
}
root type:6

```

**Comment by nanoscopic** [comment]
Does this still occur in the latest version for you? I did look into this, and 0111 within bpList is not valid for the binary plist format.

The "systemInformation" data can also be obtained via info/mg, so it is absolutely non-crucial to get the information this way. If it breaks I am not concerned.
