### ISSUE TITLE
iosif syscfg

### ISSUE THREAD

**Issue by Dantee296** [nanoscopic/iosif#6]
hi @nanoscopic when you are planing to fix syscfg so it print user readable serial numbers ? and not hex values

**Comment by Dantee296** [comment]
@nanoscopic ?

**Comment by Dantee296** [comment]
@nanoscopic are u planning to update syscfg ?

**Comment by nanoscopic** [comment]
1. I don't know what the format of syscfg data is. I partially decoded it but it still doesn't make sense to me. I need some documentation on it or some existing code capable of parsing it. If you can provide me with some information on it I can update the code to parse it correctly. If you cannot provide that information, then I have no plans to bother with it.

2. The vast majority of the data in syscfg is available within mobile gestalt ( mg ). The values there are also parsed already.

3. I myself, nor any of my paying clients have no particular need for the data within syscfg.

Essentially, it needs to be made easier for me to know how to parse, or someone needs to pay for the time necessary to research and figure it out.

Also, by the way, updating an issue repeatedly doesn't serve to convince me to work on it. It's more irritating than anything. Understandably you want answers, just be aware that I do respond to all issues eventually even if it can seem to be taking forever.

**Comment by Dantee296** [comment]
@nanoscopic i m sorry if it was irritating , thankyou for guiding me about it , i ll take care of it from now on.
sorry again
